ejemploMVC/Models/calculo.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace ejemploMVC.Models
{
    public class calculo
    {
        public int numero1 { get; set;}
        public int numero2 { get; set; }
        public int opcion { get; set; }
    }
}

ejemploMVC/Models/conversion.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace ejemploMVC.Models
{
    public class conversion
    {
        public double temperatura { get; set; }
        public double peso { get; set; }
        public double longitud { get; set; }
        public int opcion { get; set; }
    }
}

ejemploMVC/Models/promedio.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace ejemploMVC.Models
{
    public class promedio
    {
        public double nota1 { get; set; }
        public double nota2 { get; set; }
        public double nota3 { get; set; }

    }
}

ejemploMVC/Controllers/ConversionController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ejemploMVC.Models;

namespace ejemploMVC.Controllers
{
    public class ConversionController : Controller
    {
        //
        // GET: /Conversion/
        public ActionResult Index()
        {
            return View();
        }

        //POST: PRUEBA/INDEX
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Index(conversion obConversion)
        {
            //operaciones
            int opcion = obConversion.opcion;
            double resultado = 0.0;

            //1 Celsius = 274.15 Kelvin
            //1 Kelvin = -272.15 Celsius


            switch (opcion)
            {
                case 1:
                    //suma
                    resultado = obConversion.temperatura + (274.15-1);
                    ViewBag.resultado = resultado;
                    break;
                case 2:
                    //resta
                    resultado = obConversion.temperatura + (-272.15-1);
                    ViewBag.resultado = resultado;
                    break;
                case 0:
                    //Sin opcion
                    //resta
                    ViewBag.resultado = "No a seleccionado ninguna accion";
                    break;
            }

            return View(obConversion);
        }

        public ActionResult Peso(conversion obConversion)
        {
            //operaciones
            int opcion = obConversion.opcion;
            double resultado = 0.0;

            //1 lb = 0.453592 kg
            //1 kg = 2.2046 lb


            switch (opcion)
            {
                case 1:
                    //de kilos a libras
                    resultado = obConversion.peso * 2.2046;
                    ViewBag.resultado = resultado;
                    break;
                case 2:
                    //de libras a kilos
                    resultado = obConversion.peso * 0.453592;
                    ViewBag.resultado = resultado;
                    break;
                case 0:
          
                    ViewBag.resultado = "No a seleccionado ninguna accion";
                    break;
            }

            return View(obConversion);
        }

        public ActionResult Longitud(conversion obConversion)
        {
            //operaciones
            int opcion = obConversion.opcion;
            double resultado = 0.0;

            //1 m = 39.37007874 in
            //1 in = 0.0254 m


            switch (opcion)
            {
                case 1:
                    //de metros a pulgadas
                    resultado = obConversion.longitud * 39.37007874;
                    ViewBag.resultado = resultado;
                    break;
                case 2:
                    //de pulgadas a metros
                    resultado = obConversion.longitud * 0.0254;
                    ViewBag.resultado = resultado;
                    break;
                case 0:
                    ViewBag.resultado = "No a seleccionado ninguna accion";
                    break;
            }

            return View(obConversion);
        }
	}
}

ejemploMVC/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ejemploMVC.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

ejemploMVC/Controllers/PromedioController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ejemploMVC.Models;

namespace ejemploMVC.Controllers
{
    public class PromedioController : Controller
    {
        //
        // GET: /Promedio/
        public ActionResult Index()
        {
            return View();
        }

        //POST: PROMEDIO/INDEX
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Index(promedio obPromedio)
        {
            //operaciones
            double promedio = 0.0;

            promedio = (obPromedio.nota1 + obPromedio.nota2 + obPromedio.nota3)/3;

            if (promedio == 10)
            {
                ViewBag.resultado = "Felicidades has sacado la nota maxima";
            }else
                if (promedio < 10 && promedio >= 7)
                {
                    ViewBag.resultado = "Aprobado";
                }else
                    if (promedio < 7 && promedio > 4)
                    {
                        ViewBag.resultado = "Aplazado";
                    }else
                        if (promedio <= 4)
                        {
                            ViewBag.resultado = "Debe de visitar al tutor";
                        }
                        else
                        {
                            ViewBag.resultado = "Tu promedio no es el indicado";
                        }

            

            return View(obPromedio);
        }
	}
}

ejemploMVC/Controllers/PruebaController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ejemploMVC.Models;

namespace ejemploMVC.Controllers
{
    public class PruebaController : Controller
    {
        //
        // GET: /Prueba/
        public ActionResult Index()
        {
            return View();
        }

        //POST: PRUEBA/INDEX
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Index(calculo obCalculo)
        {
            //operaciones
            int opcion = obCalculo.opcion;
            int resultado = 0;

            switch (opcion)
            {
                case 1:
                        //suma
                        resultado = obCalculo.numero1 + obCalculo.numero2;
                        ViewBag.resultado = resultado;
                        break;
                case 2:
                        //resta
                        resultado = obCalculo.numero1 - obCalculo.numero2;
                        ViewBag.resultado = resultado;
                        break;
                case 3:
                        //Multiplicar
                        resultado = obCalculo.numero1 * obCalculo.numero2;
                        ViewBag.resultado = resultado;
                        break;
                case 4:
                        //Dividir
                        resultado = obCalculo.numero1 / obCalculo.numero2;
                        ViewBag.resultado = resultado;
                        break;
                case 0:
                        //Sin opcion
                        //resta
                        ViewBag.resultado = "No a seleccionado ninguna accion";
                        break;
            }
            
            return View(obCalculo);
        }
	}
}

ejemploMVC/Views/Conversion/index.cshtml
@model ejemploMVC.Models.conversion
@{
    ViewBag.Title = "index";
}

<h2>Conversiones de la temperatura</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    <div class="container mt-5">
        <div class="row">
            <div class="col-md-4">
                <div class="card">
                    <div class="card-header">
                        <div class="text-header">Conversion temperatura</div>
                    </div>
                    <div class="card-body">
                        <br /><br />
                        <div class=" form-group ">
                            @Html.LabelFor(Model => Model.temperatura, new { @class = "control-label" })
                            @Html.TextBoxFor(Model => Model.temperatura, new { @class = "form-control", type = "number", step = "0.01", required = "true" })
                        </div>
                        <br />
                        <div class="form-group">
                            <select class="form-control" name="opcion">
                                <option value="0" selected>Seleccione una conversion</option>
                                <option value="1">De celsius (ºC) a kelvin (K)</option>
                                <option value="2">De kelvin (K) a celsius (ºC)</option>
                            </select>
                        </div>
                        <div class="form-group mb-5">
                            <input type="submit" value="Calcular" class="btn btn-success" />
                        </div>
                    </div>
                    <div class="card-footer">
                    </div>
                </div>
            </div>
        </div>
    </div>
}

@if (ViewBag.resultado != null){
    <span>Resultado: &nbsp;@ViewBag.resultado</span>
}

ejemploMVC/Views/Conversion/longitud.cshtml
@model ejemploMVC.Models.conversion
@{
    ViewBag.Title = "longitud";
}


<h2>Conversiones de longitud</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    <div class="container mt-5">
        <div class="row">
            <div class="col-md-4">
                <div class="card">
                    <div class="card-header">
                        <div class="text-header">Conversion de longitud</div>
                    </div>
                    <div class="card-body">
                        <br /><br />
                        <div class=" form-group ">
                            @Html.LabelFor(Model => Model.longitud, new { @class = "control-label" })
                            @Html.TextBoxFor(Model => Model.longitud, new { @class = "form-control", type = "number", step = "0.01", required = "true" })
                        </div>
                        <br />
                        <div class="form-group">
                            <select class="form-control" name="opcion">
                                <option value="0" selected>Seleccione una conversion</option>
                                <option value="1">De metros (m) a pulgadas (in)</option>
                                <option value="2">De pulgadas (in) a metros (m)</option>
                            </select>
                        </div>
                        <div class="form-group mb-5">
                            <input type="submit" value="Calcular" class="btn btn-success" />
                        </div>
                    </div>
                    <div class="card-footer">
                    </div>
                </div>
            </div>
        </div>
    </div>
}

@if (ViewBag.resultado != null)
{
    <span>Resultado: &nbsp;@ViewBag.resultado</span>
}

ejemploMVC/Views/Conversion/peso.cshtml
@model ejemploMVC.Models.conversion
@{
    ViewBag.Title = "peso";
}

<h2>Conversiones de pesos</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    <div class="container mt-5">
        <div class="row">
            <div class="col-md-4">
                <div class="card">
                    <div class="card-header">
                        <div class="text-header">Conversion de peso</div>
                    </div>
                    <div class="card-body">
                        <br /><br />
                        <div class=" form-group ">
                            @Html.LabelFor(Model => Model.peso, new { @class = "control-label" })
                            @Html.TextBoxFor(Model => Model.peso, new { @class = "form-control", type = "number", step = "0.01", required = "true" })
                        </div>
                        <br />
                        <div class="form-group">
                            <select class="form-control" name="opcion">
                                <option value="0" selected>Seleccione una conversion</option>
                                <option value="1">De kilogramos (kg) a libras (lb)</option>
                                <option value="2">De libras (lb) a kilogramos (kg)</option>
                            </select>
                        </div>
                        <div class="form-group mb-5">
                            <input type="submit" value="Calcular" class="btn btn-success" />
                        </div>
                    </div>
                    <div class="card-footer">
                    </div>
                </div>
            </div>
        </div>
    </div>
}

@if (ViewBag.resultado != null)
{
    <span>Resultado: &nbsp;@ViewBag.resultado</span>
}

ejemploMVC/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

ejemploMVC/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

ejemploMVC/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <h1>Programacion 2</h1>
    <p class="lead">Introducción y conceptos básicos de MVC</p>
</div>

ejemploMVC/Views/Promedio/index.cshtml
@model ejemploMVC.Models.promedio
@{
    ViewBag.Title = "index";
}

<h2>Promedio por alumno</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()


    <div class="form-group">
        @Html.LabelFor(Model => Model.nota1, new { @class = "control-label" })
        @Html.TextBoxFor(Model => Model.nota1, new { @class = "form-control", type = "number", step = "0.01", min = "0", max = "10", required="true" })
    </div>

    <div class="form-group">
        @Html.LabelFor(Model => Model.nota2, new { @class = "control-label" })
        @Html.TextBoxFor(Model => Model.nota2, new { @class = "form-control", type = "number", step = "0.01", min = "0", max = "10", required = "true" })
    </div>
    
    <div class="form-group">
        @Html.LabelFor(Model => Model.nota3, new { @class = "control-label" })
        @Html.TextBoxFor(Model => Model.nota3, new { @class = "form-control", type = "number", step = "0.01", min = "0", max = "10", required = "true" })
    </div>

    <div class="form-group mb-5">
        <input type="submit" value="Calcular promedio" class="btn btn-success" />
    </div>
}

@if (ViewBag.resultado != null){
    <span>Resultado: &nbsp;@ViewBag.resultado</span>
    
}

ejemploMVC/Views/Prueba/index.cshtml
@model ejemploMVC.Models.calculo
@{
    ViewBag.Title = "index";
}

<h2>Operaciones</h2>

@using (Html.BeginForm())
{ 
    @Html.AntiForgeryToken()
    
    <div class="form-group">
        <select class="form-control" name="opcion">
            <option value="0" selected>Seleccione una operacion</option>
            <option value="1">Sumar</option>
            <option value="2">Restar</option>
            <option value="3">Multiplicar</option>
            <option value="4">Dividir</option>
        </select>
    </div>
    
    <div class="form-group">
        @Html.LabelFor(Model => Model.numero1, new { @class = "control-label" })
        @Html.TextBoxFor(Model => Model.numero1, new { @class = "form-control", type = "number", required = "true" })
    </div>
    
    <div class="form-group">
        @Html.LabelFor(Model => Model.numero2, new { @class = "control-label" })
        @Html.TextBoxFor(Model => Model.numero2, new { @class = "form-control", type = "number", required = "true" })
    </div>
    
    <div class="form-group mb-5">
        <input type="submit" value="Enviar" class="btn btn-success" />
    </div>
}

@if (ViewBag.resultado != null){
    <span>Resultado: &nbsp;@ViewBag.resultado</span>
}

ejemploMVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <title>@ViewBag.Title - Mi aplicación ASP.NET</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("GUIA DE LABORATORIO Nº 1", "Index", "Home", null, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Calculos", "index", "Prueba")</li>
                    <li>@Html.ActionLink("Conversiones temperatura", "index", "Conversion")</li>
                    <li>@Html.ActionLink("Conversiones peso", "peso", "Conversion")</li>
                    <li>@Html.ActionLink("Conversiones longitud", "longitud", "Conversion")</li>
                    <li>@Html.ActionLink("Promedio", "index", "Promedio")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Mi aplicación ASP.NET - Developing Soft</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>